name: Workflow For Docker Connect
on: push
env:
    DOCKER_USER_NAME: satish92
    DOCKER_PASSWORD: satimama
    DOCKER_HOST: dockerhub.io
    # DOCKER_IMAGE: satish-nginx
jobs:
    docker_build:
        env:
           DOCKER_IMAGE: satish-nginx  
        name: tag image
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker image build -t ${{ env.DOCKER_USER_NAME }}/$DOCKER_IMAGE:latest
        
            - name: Docker Login
              run: echo docker login --username=$DOCKER_USER_NAME --password=$DOCKER_PASSWORD --host=$DOCKER_HOST

            - name: Docker Push
              run: echo docker push docker.io/$DOCKER_USER_NAME
    
    deploy:
        name: Create Container
        needs: docker_build
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              env:
                DOCKER_IMAGE: satish-nginx2
              run: echo docker container run -d -p 8080:80  $DOCKER_HOST/$DOCKER_USER_NAME/$DOCKER_IMAGE:latest
    
    check_repo_vars:
        name: Need To Check Repo Level Vars
        runs-on: ubuntu-slim
        steps:
            - name: Check Repo Vars and Secrets
              run: |
                 echo Repo Var is ${{ vars.REPO_VAR}}
                 echo Secret Var is ${{ secrets.SECRET}}