name: First Flow
on:
   workflow_dispatch:
   push:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
    first_job:
        name: first one
        runs-on: ubuntu-latest
        steps:
           - name: Checkout Action
             uses: actions/checkout@v6
             
           - name: run hello
             run: |
               echo "Hello"
               ls -al
               cat  README.md
           - name: ASCII JOB FOR VISUAL GRAPHICS
             run: | 
                sudo apt update
                sudo apt install cowsay -y
           - name: Execute Cowsay
             run: |
                cowsay -f dragon "Run for cover, I'm a Dragon RAR" >> dragon.txt
                cat dragon.txt

           - name: Upload A Build Artifact
             uses: actions/upload-artifact@v7
             with:
                name: dragon-file-output
                path: dragon.txt

    second_job:
        name: Verify dragon.txt
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon File Artifact
              uses: actions/download-artifact@v8
              with:
                 name: dragon-file-output
            - name: print dragon file content
              run: cat dragon.txt
