name: First Flow
on: push
jobs:
    first_job:
        name: first one
        runs-on: ubuntu-latest
        steps:
           - name: Checkout Action
             uses: actions/checkout@v6
             
           - name: run hello
             run: |
               echo "Hello"
               ls -al
               cat  Readme.md
           - name: ASCII JOB FOR VISUAL GRAPHICS
             run: | 
                sudo apt update
                sudo apt install cowsay -y
           - name: Execute Cowsay
             run: |
                cowsay -f dragon "Run for cover, I'm a Dragon RAR" >> dragon.txt
                cat dragon.txt


        #    - name: list files
        #      run: ls -al

        #    - name: test if curl is present
        #      run: curl --help

    # ascii_job:
    #     name: ASCII JOB FOR VISUAL GRAPHICS
