name: Workflow To Run Docker Containers Based on Matrix Strategy
on:
   workflow_dispatch:
   push:

concurrency: 
    group: docker_info
    cancel-in-progress: true

jobs:
    docker_build:
        strategy:
          fail-fast: false
          max-parallel: 3
          matrix:
            os: [ubuntu-latest, ubuntu-22.04, windows-2022]
            images: [hello-world, alpine]
            exclude:
              - images: alpine 
                os: windows-2022
            include:
              - images: amd64/alpine
                os: ubuntu-22.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: docker info
              run: docker info
            
            - name: create container on ${{ matrix.images }} 
              run: docker run ${{ matrix.images }}
